### ISSUE TITLE
Add Code

### ISSUE THREAD

**Issue by Saon00** [KhanShaheb34/Data-Structures-and-Algorithms-Notebook-Bangla#17]

**Comment by KhanShaheb34** [comment]
কিছু অ্যাড করবি?
@Saon00

**Comment by Saon00** [comment]
Selection sort ta dekh. Ata Thik ache. Ata parle add Korte paros. Karon ei
repo te Selection sort nai

**Comment by KhanShaheb34** [comment]
তোর কাছে কি কোড আছে সিলেকশন সর্ট এর? থাকলে দিস! নাইলে আমিই ট্রাই করবো নে অ্যাড করার!

**Comment by Saon00** [comment]
@KhanShaheb34 ami to code submit korchilam, code show kore nai?
`# Time Complexity: O(n^2)
import java.util.Scanner;
public class SelectionSort {
	public static void main(String args[]) {

		Scanner scanner = new Scanner(System.in);
		System.out.print("How many numbers you want to sort: ");
		int arrayLimit = scanner.nextInt();
		int[] intArray = new int[arrayLimit];

		for (int i = 0; i < arrayLimit; i++) {
			intArray[i] = scanner.nextInt();
		}
		for (int lastIndex = intArray.length - 1; lastIndex > 0; lastIndex--) {
			int large = 0;
			for (int i = 1; i <= lastIndex; i++) {
				if (intArray[i] > intArray[large]) {
					large = i;
				}
			}
			swap(intArray, large, lastIndex);
		}
		for (int i = 0; i < intArray.length; i++) {
			System.out.println(intArray[i]);
		}
	}

	public static void swap(int[] arr, int i, int j) {
		if (i == j) {
			return;
		}
		int temp = arr[i];
		arr[i] = arr[j];
		arr[j] = temp;
	}
}
`

**Comment by KhanShaheb34** [comment]
Add kore dichi..
