### ISSUE TITLE
Arrays: The most basic concept of DSA is missing

### ISSUE THREAD

**Issue by pankajkush17** [KhanShaheb34/Data-Structures-and-Algorithms-Notebook-Bangla#18]
I want to add Arrays in the code. I will explain briefly the concepts and also write an example code for every operation on arrays for better understanding. @KhanShaheb34

**Comment by KhanShaheb34** [comment]
Sure ❤️

**Comment by pankajkush17** [comment]
Please add the "Hacktoberfest" topic to this repository. You have added
"hactoberfest" (typo error) which is not accepted

**Comment by KhanShaheb34** [comment]
Thank you
