### ISSUE TITLE
Sorting -Insertion Sort

### ISSUE THREAD

**Issue by thesurojit** [KhanShaheb34/Data-Structures-and-Algorithms-Notebook-Bangla#19]
#### Code
#include <math.h>
#include <stdio.h>
void insertionSort(int arr[], int n)
{
	int i, key, j;
	for (i = 1; i < n; i++) {
		key = arr[i];
		j = i - 1;

		/* Move elements of arr[0..i-1], that are
		greater than key, to one position ahead
		of their current position */
		while (j >= 0 && arr[j] > key) {
			arr[j + 1] = arr[j];
			j = j - 1;
		}
		arr[j + 1] = key;
	}
}

void printArray(int arr[], int n)
{
	int I;
	for (i = 0; i < n; i++)
		printf("%d ", arr[i]);
	printf("\n");
}

int main()
{
	int arr[] = { 12, 11, 13, 5, 6 };
	int n = sizeof(arr) / sizeof(arr[0]);

	insertionSort(arr, n);
	printArray(arr, n);

	return 0;
}

**Comment by UTKARSHMOHAN2003** [comment]
please assign me this issue i want to work on this insertion sort  in  C language .

**Comment by KhanShaheb34** [comment]
@UTKARSHMOHAN2003 assigned
