### ISSUE TITLE
Add code for Stack data structure

### ISSUE THREAD

**Issue by Javali-M** [KhanShaheb34/Data-Structures-and-Algorithms-Notebook-Bangla#24]
#### Name 
Implementing stack data structure using arrays

#### Language
C++

#### Note 
More algos and programs on stack data structure can be added. The files can be added to the BasicDataStructures folder.

**Comment by Javali-M** [comment]
Please assign this issue to me @KhanShaheb34 , I'll be happy to work on it.

**Comment by KhanShaheb34** [comment]
@Javali-M Assigned. 😊

**Comment by UTKARSHMOHAN2003** [comment]
assign me please

**Comment by KhanShaheb34** [comment]
@Javali-M is already assigned

**Comment by Javali-M** [comment]
I have completed the pull request for this issue. @KhanShaheb34 , May I please know if I should close this issue since mine has been merged successfully?

**Comment by KhanShaheb34** [comment]
Ok. I'm closing the issue then.
