### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by Fluorospek** [KhanShaheb34/Data-Structures-and-Algorithms-Notebook-Bangla#42]
Name: Shell Sort

Language: C++

Please assign this issue to me

**Comment by Fluorospek** [comment]
Please add hacktoberfest tag too

**Comment by KhanShaheb34** [comment]
Added @Fluorospek

**Comment by vader22a** [comment]
pls see i have created shell sort program with proper description and algorithm 
pls merge it with me
