### ISSUE TITLE
reverse a string in java

### ISSUE THREAD

**Issue by saksham-29** [KhanShaheb34/Data-Structures-and-Algorithms-Notebook-Bangla#85]
import java.io.*;
import java.util.Scanner;

class abc {
	public static void main (String[] args) {
		
		String str= "zxcv", nstr="";
		char ch;
		
	System.out.print("Original word: ");
	System.out.println("zxcv"); //Example word
		
	for (int i=0; i<str.length(); i++)
	{
		ch= str.charAt(i); //extracts each character
		nstr= ch+nstr; //adds each character in front of the existing string
	}
	System.out.println("Reversed word: "+ nstr);
	}
}

**Comment by KhanShaheb34** [comment]
Please give a PR
